version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: file-upload-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fileupload
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-upload-app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/fileupload
      - CLOUD_STORAGE_ENABLED=false
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data: